### ISSUE TITLE
The Install Haxelib Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-PsychEngine-With-Android-Support-Archive#1]
### Describe your bug here.

I Just Trying To Compile, But It's Still 
![Screenshot_20220817-192136~2](https://user-images.githubusercontent.com/109828559/185203546-d5a021b6-e878-488a-83e1-af1136054bce.png)
Error

So, Can You Help Me?

### Command Prompt/Terminal logs (if existing)

-4277821/linc_luajit.git

2022-08-17T18:49:23.2303382Z Error: Could not clone Git repository.

2022-08-17T18:49:23.2329322Z ##[error]Process completed with exit code### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, I Just Trying To Fix This, But I Can't :(

**Comment by Hiho2950** [comment]
change in workflows files :
https://github.com/jigsaw-4277821/linc_luajit.git
make it :
https://github.com/AndreiRudenko/linc_luajit.git
and try
