### ISSUE TITLE
The main.yml Fix

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-PsychEngine-With-Android-Support-Archive#3]
### What feature do you want to get added on the **base** engine?

Hello, It's Me, StefanBETA. I just Tried 2 Hours To Fix The Problem With The Installation With The Haxelib. Just Rename This:
![Screenshot_20220817-224217~2](https://user-images.githubusercontent.com/109828559/185239288-fdea43fb-da89-4638-932c-15fa7ab5e11a.png)
To Your New Code: https://github.com/MAJigsaw77/linc_luajit

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by Hiho2950** [comment]
i m already know this before 1 minute of you say thats and thanks

**Comment by StefanBETA2008** [comment]
It's Working For My Engine

**Comment by Hiho2950** [comment]
me too its working now

**Comment by StefanBETA2008** [comment]
Than, Saw Has Need To Fix This Problem Wit main.yml

**Comment by Hiho2950** [comment]
yes .when you have finish your engine i will try it

**Comment by StefanBETA2008** [comment]
It's Psych Engine, But On Serbian Language

**Comment by StefanBETA2008** [comment]
And You Have On The MainMenuState Character

**Comment by Hiho2950** [comment]
oh ok i dont know the serbian language

**Comment by Hiho2950** [comment]
now i try to port this
https://github.com/LoudSilencer/FNF-Undertale-Source-Code

**Comment by StefanBETA2008** [comment]
https://github.com/StefanBETA2008/SB-Engine Here It's My Engine. I Will And On My Engine New Updates. It's Old Saw Repository, But I Don't Deleted

**Comment by Hiho2950** [comment]
i have see it

**Comment by StefanBETA2008** [comment]
Damn, I Need PC For This

**Comment by Hiho2950** [comment]
for try it or you find its hard to do it on mobile

**Comment by StefanBETA2008** [comment]
![Screenshot_20220812-232538](https://user-images.githubusercontent.com/109828559/185241978-2fd27eef-9050-45d9-97fb-da091a49c45c.png)
Can You Doit This 😏

**Comment by StefanBETA2008** [comment]
> ![Screenshot_20220812-232538](https://user-images.githubusercontent.com/109828559/185241978-2fd27eef-9050-45d9-97fb-da091a49c45c.png) Can You Doit This 😏

It's Working 100%, But I Need To Move Coordinate's 😅

**Comment by Hiho2950** [comment]
idk i think you see eit's pe tutorials

**Comment by Hiho2950** [comment]
in youtube

**Comment by StefanBETA2008** [comment]
> idk i think you see eit's pe tutorials

Yeah, But I Just Tried To Add The Animated Background On MainMenuState, But It's Still Showing The HaxeFlixel Mini Logo On The Center. Can You Show Me How To Fix It?

**Comment by Hiho2950** [comment]
if the file is not founded it will do like thats

**Comment by StefanBETA2008** [comment]
> if the file is not founded it will do like thats

I Need The Image To The Work Or?

**Comment by Hiho2950** [comment]
try to see the os engine i try it
his omptimization is better than psych engine

**Comment by Hiho2950** [comment]
i think thats

> > if the file is not founded it will do like thats
> 
> I Need The Image To The Work Or?

**Comment by StefanBETA2008** [comment]
> try to see the os engine i try it his omptimization is better than psych engine

I Will Find Later. I Need To See It's This Working Now

**Comment by Hiho2950** [comment]
ok

**Comment by StefanBETA2008** [comment]
I Will Close This Issue Now. Thank You 👋🏻. See You Later.

**Comment by Hiho2950** [comment]
bye

**Comment by StefanBETA2008** [comment]
Hello, I Just 

> try to see the os engine i try it his omptimization is better than psych engine

Can You Share The Image, Please?

**Comment by StefanBETA2008** [comment]
> Hello, I Just Trying To Find The Image.
> 
> > try to see the os engine i try it his omptimization is better than psych engine
> 
> Can You Share The Image, Please?

For The Animated Background On MainMenuState.
