### ISSUE TITLE
It closes when entering a song

### ISSUE THREAD

**Issue by FabianInayao** [MAJigsaw77/FNF-PsychEngine-With-Android-Support-Archive#6]
### Describe your bug here.

E

### Command Prompt/Terminal logs (if existing)

```bash
E
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FabianInayao** [comment]
It only happens to me in the 6.2

**Comment by Gabrix19800** [comment]
Bro when i go to a Song It doesn't play

**Comment by StefanBETA2008** [comment]
What Do You Mean? It's Everything Working Fine. 😑
