### ISSUE TITLE
Help me Phone 2GB Ram Lag 

### ISSUE THREAD

**Issue by Vietanhd10** [MAJigsaw77/FNF-PsychEngine-With-Android-Support-Archive#8]
### Describe your problem here.

Ram 2GB Ram Lag 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by Vietanhd10** [comment]
I hope 0.6.2 will reduce the lag note, but it's very laggy, what version is
there?

Vào 9:02 CH, Th 2, 12 thg 9, 2022 BonnyeBonbox ***@***.***>
đã viết:

**Comment by StefanBETA2008** [comment]
You Can't Run On 2GB Of Ram. Only On 4GB's

**Comment by MAJigsaw77** [comment]
> You Can't Run On 2GB Of Ram. Only On 4GB's

Exactly
