### ISSUE TITLE
what about the resolution of the game and its icon?

### ISSUE THREAD

**Issue by Fearester** [MAJigsaw77/FNF-PsychEngine-With-Android-Support-Archive#9]
### Describe your bug here.

what about the resolution of the game and its icon?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Fearester** [comment]
![Uploading Screenshot_20220917-161703.jpg…]()

**Comment by StefanBETA2008** [comment]
I Can't See The Screenshot

**Comment by Fearester** [comment]
![Screenshot_20220917-161703](https://user-images.githubusercontent.com/111678905/190867290-9e2a334e-2530-4e49-acef-243b524b4526.jpg)
![Screenshot_20220917-161314](https://user-images.githubusercontent.com/111678905/190867293-ca222c6b-6946-49fa-b8f2-2f89448f845d.jpg)

**Comment by Fearester** [comment]
> I Can't See The Screenshot

**Comment by StefanBETA2008** [comment]
> ![Screenshot_20220917-161703](https://user-images.githubusercontent.com/111678905/190867290-9e2a334e-2530-4e49-acef-243b524b4526.jpg) ![Screenshot_20220917-161314](https://user-images.githubusercontent.com/111678905/190867293-ca222c6b-6946-49fa-b8f2-2f89448f845d.jpg)

You Need To Add `lime 7.9.0` For Icon And The `openfl 9.1.0` For The Resolution On main.yml

**Comment by Fearester** [comment]
![Screenshot_20220918-055136](https://user-images.githubusercontent.com/111678905/190884751-36c2a458-209e-4804-91b8-1916d8a9e88e.jpg)


> :(

**Comment by StefanBETA2008** [comment]
> ![Screenshot_20220918-055136](https://user-images.githubusercontent.com/111678905/190884751-36c2a458-209e-4804-91b8-1916d8a9e88e.jpg)
> 
> > :(

Yeah, You Need To Update The SUtil.hx

**Comment by StefanBETA2008** [comment]
> > ![Screenshot_20220918-055136](https://user-images.githubusercontent.com/111678905/190884751-36c2a458-209e-4804-91b8-1916d8a9e88e.jpg)
> > > :(
> 
> Yeah, You Need To Update The SUtil.hx

If You Know How To Give Me Permission To Edit The SUtil.hx, I Can Help

**Comment by Fearester** [comment]
how?

**Comment by Fearester** [comment]
> 

Yes

**Comment by StefanBETA2008** [comment]
> how?

Go To Settings To Your Repository, Than Find This Options:
![Screenshot_20220918-110316~2](https://user-images.githubusercontent.com/109828559/190894428-949fc251-9dc0-472b-885d-ee7739d56594.png)
Than, Go Type Mu Username For GitHub. My Username It's: StefanBETA2008 And Then Type You Repository Name

**Comment by Fearester** [comment]
I made you a collaborator

**Comment by StefanBETA2008** [comment]
> I made you a collaborator

Thanks. Now I Can Fix Your Problem With The Icon And The Resolution

**Comment by Fearester** [comment]
![Uploading Screenshot_20220918-122528.jpg…]()

**Comment by StefanBETA2008** [comment]
I Think I Fixed

**Comment by Fearester** [comment]
give me your discord

**Comment by StefanBETA2008** [comment]
> give me your discord

Stefan[BETA]™#3681

**Comment by Fearester** [comment]
Your privacy is closed add me as a friend!

**Comment by StefanBETA2008** [comment]
> Your privacy is closed add me as a friend!
> 
> >

Username?

**Comment by Fearester** [comment]
![Screenshot_20220918-154241](https://user-images.githubusercontent.com/111678905/190902613-71e3aa7f-e2b9-44e4-a4f7-c9962cb766ab.jpg)

**Comment by StefanBETA2008** [comment]
> Your privacy is closed add me as a friend!
> 
> >

Yours Username?

**Comment by StefanBETA2008** [comment]
Dude, You Can Now Close This Issue Now.
